### ISSUE TITLE
stack_for_ilias7 setup fails with 'assStackQuestionException' not found

### ISSUE THREAD

**Issue by Lennart-Kramer** [ilifau/assStackQuestion#94]
We are trying to make a testing setup for stack and installing the latest commit of stack_for_ilias7 on a new instance causes following error:
```
[69b52] [2022-08-17 16:25:28.150684] default_root.ERROR: ilErrorHandling::{closure}:50 0 Class 'assStackQuestionException' not found in /var/www/html/Customizing/global/plugins/Modules/TestQuestionPool/Questions/assStackQuestion/classes/locallib.php:24#0 /var/www/html/Customizing/global/plugins/Modules/TestQuestionPool/Questions/assStackQuestion/classes/utils/class.assStackQuestionInitialization.php(33): include_once()
#1 /var/www/html/Customizing/global/plugins/Modules/TestQuestionPool/Questions/assStackQuestion/classes/model/configuration/class.assStackQuestionConfig.php(481): require_once('/var/www/html/C...')
#2 /var/www/html/Services/Database/classes/class.ilDBUpdate.php(504) : eval()'d code(47): assStackQuestionConfig->setDefaultSettingsForConnection()
#3 /var/www/html/Services/Database/classes/class.ilDBUpdate.php(504): eval()
#4 /var/www/html/Services/Database/classes/class.ilDBUpdate.php(371): ilDBUpdate->applyUpdateNr(18)
#5 /var/www/html/Services/Component/classes/class.ilPlugin.php(526): ilDBUpdate->applyUpdate()
#6 /var/www/html/Services/Component/classes/class.ilPlugin.php(1087): ilPlugin->updateDatabase()
#7 /var/www/html/Services/Component/classes/class.ilObjComponentSettingsGUI.php(507): ilPlugin->update()
#8 /var/www/html/Services/Component/classes/class.ilObjComponentSettingsGUI.php(458): ilObjComponentSettingsGUI->update(Object(ilassStackQuestionPlugin))
#9 /var/www/html/Services/Component/classes/class.ilObjComponentSettingsGUI.php(123): ilObjComponentSettingsGUI->installPlugin()
#10 /var/www/html/Services/UICore/classes/class.ilCtrl.php(217): ilObjComponentSettingsGUI->executeCommand()
#11 /var/www/html/Services/Administration/classes/class.ilAdministrationGUI.php(246): ilCtrl->forwardCommand(Object(ilObjComponentSettingsGUI))
[Wed Aug 17 14:25:28.150887 2022] [php7:notice] [pid 59] [client 172.30.1.1:61709] Class 'assStackQuestionException' not found, referer: http://[removed]/ilias.php?ref_id=31&admin_mode=settings&cmd=view&cmdClass=ilobjcomponentsettingsgui&cmdNode=1d:lf&baseClass=ilAdministrationGUI
#12 /var/www/html/Services/UICore/classes/class.ilCtrl.php(217): ilAdministrationGUI->executeCommand()
#13 /var/www/html/Services/UICore/classes/class.ilCtrl.php(178): ilCtrl->forwardCommand(Object(ilAdministrationGUI))
#14 /var/www/html/ilias.php(23): ilCtrl->callBaseClass()
#15 {main}  
```

Versions:
```
php: php7.4
ilias: 7.12
assStackQuestion: dffc3c63fef4e66dcf75e65c20303aab61c36250 (stack_for_ilias7)
```

**Comment by jcopado** [comment]
Having a look on it, expect a bugfix version today or tomorrow at latest
Thanks for the report!

**Comment by Lennart-Kramer** [comment]
Thanks for the quick response!
I tested 6.8 in a fresh instance and unfortunately it still seems to throw the same error.

**Comment by jcopado** [comment]
Hi Lennart, new bugfix version, 6.8.1, I hope this time works.

**Comment by Lennart-Kramer** [comment]
I have tried 6.8.3 and setup works now, thank you!
